### ISSUE TITLE
BOTÓN HOJA DE RUTA

### ISSUE THREAD

**Issue by teresa2017EC** [kplian/sis_correspondencia#11]
El botón de Hoja de Ruta a veces muestra un archivo .pdf, otras veces no, otras se detiene el sistema. Como requerimiento se requiere que se habilite una misma ventana dentro la aplicación para poder ver esto, debido a q demora la visualización actual y se muestra en otra ventana del navegador.

**Comment by fprudencio** [comment]
Para la generación de todos los reportes del sistema es necesario tener los navegadores configurados para abrir ventanas emergentes del servidor donde se aloja el sistema.

**Comment by teresa2017EC** [comment]
No se encuentra el boton hoja de ruta para prueba
