### ISSUE TITLE
REDERIVACIÓN DE DOCUMENTO

### ISSUE THREAD

**Issue by teresa2017EC** [kplian/sis_correspondencia#18]
Al rederivar un documento recibido, muestra mensaje de error.

**Comment by rensi4rn** [comment]
Rederivar no es posible principalmente por que  genera un bucle,
 ademas de que no es  necesario por  que ya tiene el  documento digital,

**Comment by teresa2017EC** [comment]
Se deja pendiente esta observación hasta realizar un nueva prueba
