### ISSUE TITLE
REGISTRO DE DOCUMENTO

### ISSUE THREAD

**Issue by teresa2017EC** [kplian/sis_correspondencia#22]
QUITAR LAS COLUMNAS FUNCIONARIO REMITENTE, UO REMITENTE EN ENTRENTE (EXTERNA RECIBIDA).

**Comment by fprudencio** [comment]
Se ocultaron los campos indicados en la vista EXTERNA RECIBIDA

**Comment by teresa2017EC** [comment]
Se verifico que en BANDEJAS de correspondencia interna se visualizan las columnas funcionario remitente y UO remitente. Gracias.

Solicito la visualización de las columnas INSTITUCIÓN O PERSONA REMITENTE en ENTRENTE (EXTERNA RECIBIDA)
