### ISSUE TITLE
IMPRIMIR CÓDIGO

### ISSUE THREAD

**Issue by teresa2017EC** [kplian/sis_correspondencia#25]
NO MUESTRA UNA VISTA PREVIA DE LO QUE SE VA IMPRIMIR.

**Comment by fprudencio** [comment]
Se crearon dos opciones de recepción. 
La primera para imprimir un sticker que se pueda pegar a los documentos recepcionados y la otra una impresión directa a los documentos.
Ambos contienen la misma información.

**Comment by teresa2017EC** [comment]
EN ESTAS OPCIONES SE OBSERVA UNA VENTANA QUE INDICA LO SIGUIENTE:
Mensaje: permiso denegado para la transacción

Por este motivo no se puede realizar un prueba. Por favor solicito el pronto acceso a esto.
