### ISSUE TITLE
BANDEJA - EMITIDA - ELIMINAR

### ISSUE THREAD

**Issue by teresa2017EC** [kplian/sis_correspondencia#3]
Al eliminar un registro en Bandejas - emitida muestra un error

**Comment by fprudencio** [comment]
Se soluciono la funcionalidad de eliminar registros en la bandeja, pero se puso la restricción de que solo se puede eliminar si el estado de la correspondencia es borrador.

**Comment by teresa2017EC** [comment]
Se requiere opciones de corrección y eliminación en cualquier estado

**Comment by rensi4rn** [comment]
No es posible por motivos de seguridad, 
tenemos que ver la funcionalidad para todos. 
Podemos hacer como en la versión de ENDE,  crear una  interface  para rescatar números anulados y cambiar el responsable, esta interface solo podría tener la secretaria principal de la empresa o el feje de correspondencia.

**Comment by teresa2017EC** [comment]
Si habra un responsable de esta acción. Sin embargo queda abierta esta solicitud previa consulta con los jefes.
