### ISSUE TITLE
BANDEJAS - EMITIDA - HOJAS DE RUTA

### ISSUE THREAD

**Issue by teresa2017EC** [kplian/sis_correspondencia#4]
Muestra error al solicitar hoja de ruta, sin embargo en algunos computadoras no se visualiza el error. Solicitamos que funcione con todos los navegadores y todas la versiones.

**Comment by fprudencio** [comment]
El sistema funciona en las ultimas versiones de Chrome y Mozilla Firefox. No funciona en Internet Explorer debido a que este navegador no cumple con los estandares de HTML5.

**Comment by teresa2017EC** [comment]
No se visualiza el boton hoja de ruta para realizar la prueba
